### ISSUE TITLE
com.github.nkzawa.engineio.client.EngineIOException: xhr post error

### ISSUE THREAD

**Issue by sanakanchha** [socketio/socket.io-client-java#101]
Hi,
I am using this library to connect to the v 1.3.3 socketIO server. The device gets connected initially which is great and immediately gets disconnected. I am getting the following error.
com.github.nkzawa.engineio.client.EngineIOException: xhr post error

Has anyone come across this issue before? Any help appreciated. Thanks.

**Comment by nkzawa** [comment]
I'm sorry for the delay. Need more information. How can I reproduce the problem?

**Comment by oriharel** [comment]
Happens here too. I'm connecting from an Android background service to my socket server.
Here are the options:

IO.Options opts = new IO.Options();
opts.path = "/relay.bus/socket.io";
opts.forceNew = true;

mSocket = IO.socket(url, opts);
mSocket.connect();

**Comment by brucexia0** [comment]
Getting the same error here:
            mSocket = IO.socket("http://chat." + ConstantsNetwork.BASE_URL);
            mSocket.connect()
Library version: 
compile('com.github.nkzawa:socket.io-client:0.3.0') {
        exclude group: 'org.json', module: 'json'
    }

**Comment by endlessmind** [comment]
I've having similar issue. Connects to server. Gets a few row of data, then get this error.
The library will reconnect, but after receiving the initial data, it will throw the exception again.
I'm just using the standard setup:s =  IO.socket(url); s.connect(); with a few listeners.
Look like the xhr polling want to do a post-request while the data stream is open?
I'm not familiar with the protocol in use with this kind of connections tho.

**Comment by endlessmind** [comment]
To add more info:
When inspecting the network activity in chrome (F12) I'm seeing frame like this:
Sending : "2"
Receiving: "3"
Image where: http://gyazo.com/92cbce926c775f25a7416146dc766328
There are 25-ish sec between each transmission.

When establishing the first connection, then server returns this:
{"sid":"f1e55711-c6b2-4de8-b5f8-487633baa3cb","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}

From that I believe that each transmission is a ping-pong operation, correct?

The thing is, that I'm connecting to an external server that I have not control over.
But, the ping-pong calls are the same as they once to/from my own test-server.

While inspecting the javascript on the site I'm getting data from (socket.io client code), I could not see anything weird. This has been confirmed by me connecting to the external server with the same javascript code I've been using for my test-server and client setup.

While connected to my test-server with this library, I don't get any xhr post error...

To test this, connect to http://scorebot.hltv.org:10022/

On "connect" (or Socket.EVENT_CONNECT), send "emit("readyForMatch", 364081);"
(You could also register listeners for: "log", "score" and "scoreboard", but you'll only get empty arrays because their data as expired)

This will return empty arrays, but the same xhr post error occurs when arrays are not empty.

Hope this is data enough. The xhr post error is really bugging me..

**Comment by nkzawa** [comment]
@endlessmind sorry I have no idea about that. Can you ask the issue to people who own the external server?

**Comment by endlessmind** [comment]
The owner of the external server, won't answer me.
But as I am able to have a successful connection via Socket.IO in javascript, shouldn't that mean that It's something to do with the library?

What are the post-request even doing? It that the ping-pong or is that handled by a open data-stream? (Chrome shows me an open websocket where all data is received in frames)

**Comment by nkzawa** [comment]
@endlessmind still not sure where is the cause since you can connect to your test server and usually this problem doesn't happen.

Post request is used for sending data on polling transport.

**Comment by endlessmind** [comment]
When checking the status code of the request that fails, it turns out to be 500. So internal server error..
But why don't I get that when connecting with javascript... It's just like the library is making a post-request when the server isn't expecting it.

**Comment by endlessmind** [comment]
I've now comfirmed that It's an issue with this library. 
Made a test-app using this library for C#: https://github.com/Quobject/SocketIoClientDotNet

And there I've no problems at all.

Also, here its the javascript file for the client-side that the external server uses
http://static.hltv.org//js/scorebot3.js

As you can see, nothing strange at all there.

The server is running Socket.IO 1.3.5.

**Comment by nkzawa** [comment]
@endlessmind It would be an issue with this library, but there are other differences like HTTP Header which the server should accept.
We'd love to fix the issue if we can, but anyway need to know the cause and reproduce it.

**Comment by endlessmind** [comment]
I would love to help as much as I can. Weren't you able to reproduce the issue with the info i provided in an earlier post?

I've been thinking ofr the http headers also. Mostly the User-Agent. I had issue with the while handling request to former Groovesharks site. Their site didn't like the Android (or any mobile OS) User-Agent. 

Checking the headers, the request headers seams empty (what?)
I'm iterating over xhr.getRequestProperties() after the request properties has been set.
At one point, it actually contains one property: Content-type: application/octet-stream

But the typical response headers looks like this (Even when I add User-Agent for desktop)
http://gyazo.com/4456d1c9f89fa115828ff49b1aa8c9c2

I don't know how, but the server still knows that it's an Android device..Maybe something with okHttp?

But when the error occurs, the response headers are way smaller (Only the Android stuff):
http://gyazo.com/6c4227600296a9b14d91e69e5424800c

I suspect that okHttp is adding some headers. I'm not sure. But it's strange that I can't see any request headers (like content-lenght) other than the once we set manually..Any particular reason you're using okHttp instead of Android own http client api?

**Comment by nkzawa** [comment]
@endlessmind The problem is we have to reproduce the server side error to detect the cause,  even if it's the fault of this library. 

I think OKHttp and HTTPConnection would set default User-Agent and other headers if you don't set any values.

**Comment by endlessmind** [comment]
Aight, I can see that.

But, about the headers, when I set a custom User-Agent header, is should not be overwritten by OkHttp or HttpConnection. So I don't understand how the server still where able to classify it as an Android-client. 

I found a different library that worked (based on the Java-WebSocket library). I'm not doing anything fancy with Websocket, just listening for incoming test. So I don't see any need to be able to handle binary data and other stuff like that.

But thanks for your hard work and for taking the time to respond.

**Comment by nkzawa** [comment]
> I found a different library that worked (based on the Java-WebSocket library).

can I ask which library is it?

**Comment by endlessmind** [comment]
I thinks it was this one:
https://github.com/artemisia-absynthium/socket.io-java-client

Had to make some changes, it's parseing the incoming data a bit wrong (maybe not the same fork as I cloned) and it want to connect to url + "socket.io/1/?EIO=2" or something like that. Maybe it works on some servers, but I needed: url + "socket.io/?EIO=3" (+ the transport and sid parameters)

**Comment by oliverhausler** [comment]
@endlessmind Did you find our more? I am seeing exactly the same problem (see #193) and I believe it only happens on specific Android versions or devices.

**Comment by endlessmind** [comment]
Nope. I had the same problem on all my devices (Samsung, Sony, Asus).
That's why i switched to an other library, and as it's working now I've also not tested any newer commit of this library.

**Comment by oliverhausler** [comment]
Yes, I have realized I'm having the problems on all devices as well. Just not with the same frequency. @endlessmind Which library are you using, instead?

**Comment by endlessmind** [comment]
I'm using this library (might be the wrong fork, don't remember) 
https://github.com/artemisia-absynthium/socket.io-java-client

But it needed some modification, as described in an earlier post above.

**Comment by nirhart** [comment]
I'm having the same problem - any directions?

**Comment by efkan** [comment]
So far I encountered with this issue just one time.

@nkzawa , I guess [xhr post error](https://github.com/socketio/engine.io-client-java/blob/732308bafe66f9393d003f58b8c33a8eec804708/src/main/java/io/socket/engineio/client/transports/PollingXHR.java#L86) is a common issue which is not specific.

We can try to re-connect the socket right? 
Or would you recommend trying re-connect the socket again?

**Comment by X-NicON** [comment]
options **requestTimeout** set to 20000

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
