### ISSUE TITLE
How To handle Error for specific emit

### ISSUE THREAD

**Issue by MohamedHatemAbdu** [socketio/socket.io-client-java#118]
If i want to handle error for specific emit request what i should do ?, cause any failure in any emit calls the listener of EVENT_CONNECT_ERROR, i am in need of urgent reply.

**Comment by nkzawa** [comment]
You can't detect which emit call causes the error. Why you need that?

**Comment by MohamedHatem** [comment]
I am implementing instant messaging application, so when one user sends messages to another user i need to know if this message has arrived to other side successfully or something went wrong like (failure in connection not acknowledgement from served side).

in general , i need to know any emit i am sending it went successfully or failed for something like server error ( failure in connection).

What i want that 
emit(Event, Object , CallbackMethod ) since "CallbackMethod" notifies me in the two cases if the emit succeed or failed , and if failed it says what the type of failure (like connection error).

Note : 
Ack = >  notifies me as long as the connection is live with the server, but if there is no connection i don't know if the message has failed to arrive or not.

**Comment by adaltavo** [comment]
Did you find a solution to this?, I'm facing a similar problem

**Comment by habibullah-26** [comment]
Any one find this solution, please share

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
