### ISSUE TITLE
Ping pong question

### ISSUE THREAD

**Issue by Alex--Kang** [socketio/socket.io-client-java#145]
Hi,
I noticed one thing in our recent testing.
Here we have android 5.0/4.4 with socket.io 0.5.0 

when the mobile phone is active ( screen is on), our Heroku server got ping and send pong every 25 seconds. 
however, when the mobile phone is idle with screen-off, server does not receive the ping no more, and the connection will be lost.
I wonder if there Is a way to force sending ping packet from the client side ? 

Thank you

**Comment by nkzawa** [comment]
I'm not sure, but maybe you have to use a background service for that?

**Comment by Alex--Kang** [comment]
Yes, that's our strategy right now - background service.
but for some reason, whenever the phone is idle, the ping-pong stopped, and disconnect-reconnect starts..  I wonder if anyone else notice the same thing.

**Comment by nllptr** [comment]
@Alex--Kang What kind of service are you using? We had similar problems with IntentService. When switching to Service things work nicely.

**Comment by joshimohit** [comment]
P.S. : If your service is running in this case or not. because when service
is in background, android system might decide to stop the service. You
might have disconnected the socket in onDestroy method of service.

Read this for how android system manages Application components:

http://developer.android.com/guide/components/processes-and-threads.html

You may need to specify Service.START_STICKY
<http://developer.android.com/reference/android/app/Service.html#START_STICKY>
and Service.START_REDELIVER_INTENT.
<http://developer.android.com/reference/android/app/Service.html#START_REDELIVER_INTENT>
Doing this make sures that your service is restarted when android system
decides to. Also read this to know more about services:
http://developer.android.com/guide/components/services.html



<http://developer.android.com/reference/android/app/Service.html#START_REDELIVER_INTENT>

**Comment by MohamedHatem** [comment]
I am facing the same problem, may you clarify where I have to use the service ? to solve this problem.

P.S : this problem occurring with me in some devices  and doesn't occur with other device.

**Comment by roninhack** [comment]
AsyncTask and recursive function (detect internet or interval etc..) maybe solution,

**Comment by Abdohurbly** [comment]
I'm facing the same problem.. any idea ?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
