### ISSUE TITLE
SSL/TLS is 2-3x slower than unsecured connection

### ISSUE THREAD

**Issue by MaxHastings** [socketio/socket.io-client-java#188]
There's a huge increased delay in socket.io communication when using SSL/TLS. I recorded how long it took the client to emit a message and get a response back from the server which took 3x longer when using SSL instead of an unsecured connection. This SSL delay does not happen when using socket.io on the web, so it must be something with my app code or this socket.io java client. Why is this happening and how do I fix it?

```
private TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
    public java.security.cert.X509Certificate[] getAcceptedIssuers() {
        return new java.security.cert.X509Certificate[]{};
    }

    public void checkClientTrusted(X509Certificate[] chain,
                                   String authType) throws CertificateException {
    }

    public void checkServerTrusted(X509Certificate[] chain,
                                   String authType) throws CertificateException {
    }
}};

public static class RelaxedHostNameVerifier implements HostnameVerifier {
    public boolean verify(String hostname, SSLSession session) {
        return true;
    }
}

@Override
public void onCreate (){
    super.onCreate();
    SSLContext sc = SSLContext.getInstance("TLS");
    sc.init(null, trustAllCerts, new SecureRandom());
    IO.setDefaultSSLContext(sc);
    HttpsURLConnection.setDefaultHostnameVerifier(new RelaxedHostNameVerifier());
    opts = new IO.Options();
    opts.sslContext = sc;
    opts.secure = true;
    mSocket = IO.socket(address, opts);
    mSocket.connect();
}
```

**Comment by nkzawa** [comment]
Umm, sorry, I have no idea about that.

**Comment by joshimohit** [comment]
@maxwell10206  Correct SSL is supposed to be slower than unsecured connection... it may be because when we establish SSL connection first handshake and security connection gets established and then ur socket connection takes place. However once SSL handshaking is completed successfully, Subsequent connect/disconnect are faster. @nkzawa can you please see if there can be some improvements in library ? Our general observation is when we make socket connection: 

1. using SSL for very first time on Slower (2G) network it takes approx 6-8 minutes for socket to get connect.  where as it takes 1-2 minutes for socket to get connect (first time) on Slower

**Comment by maxwell10206** [comment]
@joshimohit The speed decrease it hardly noticeable using a secured connection on web socket.io. Maybe 10-20% slower? Unfortunately with my app it's 100-150% slower. This does not only happen when establishing a connection to the server, this slow speed happens when emitting and receiving events too! :(

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
