### ISSUE TITLE
'disconnect' is not called

### ISSUE THREAD

**Issue by askarsyzdykov** [socketio/socket.io-client-java#213]
hi,

1) the client is connected to the server via Wi-Fi
2) I disconnect the internet, but not Wi-Fi
3) 'disconnect' is not called long time
4) emits sent without error

how to check that there is no Internet?

tnx for response

**Comment by nkzawa** [comment]
That's the expected behavior. Socket.IO periodically checks if a connection is still alive or not. You can change the interval of it by the `pingInterval` option on server side.
See https://github.com/socketio/engine.io#methods-1 .

For Android, see https://developer.android.com/training/basics/network-ops/managing.html to check if there is internet connection.

**Comment by nkzawa** [comment]
Closed due to inactivity. Feel free to reopen the issue.
