### ISSUE TITLE
Battery Worries

### ISSUE THREAD

**Issue by soulbeing** [socketio/socket.io-client-java#267]
Hei, I just want to know if the socket.io will take too much battery if I keep listening on coming message from server 24/7 as long as connect to Wifi? 

And by the way, in cases of changing IP and Port, how can the socket reconnected automatically??

**Comment by mrzulkarnine** [comment]
I don't have answer for your first question but I do have a suggestion on how to make socket reconnected automatically on android app using GCM. (I never implemented this, but I think you can give a try)

1. Store the IP address and port number in remote database.
2. Fetch the stored IP address and port number and store it locally.
3. Use the stored IP & port to connect to your socket
4. When connecting to the remote socket, send a GCM token to the server and stored it locally.
5. IF the IP/port is changed later, update the remote database with the new one. Notify the app via GCM and fetch the no. from remote database and reconnect again.

For workarond solution, usually I will use Domain Name instead of IP address and make sure my port number not use by any other app such as  (postgres, http etc)

You can refer to this, https://developers.google.com/cloud-messaging/android/client & http://developer.android.com/guide/components/services.html 

I hope this can help you or might be someone else in this Github can improve my answers or give better solution than me.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
