### ISSUE TITLE
Emit or Ack timeout handling?

### ISSUE THREAD

**Issue by engineers-bojan** [socketio/socket.io-client-java#309]
Is there a suggested way how to implement or handle this issue?

The iOS client version has the timeout option, but there is none found on Android SDK. 

Without it, we are experiencing difficulties handling use cases where network connectivity is low and sockets are emitted but there are no callbacks if the emit was successful....

**Comment by wedneyyuri** [comment]
> There is no timeout for ACK on socket.io. You need to implement it if required.

See #204 and https://github.com/socketio/socket.io/issues/828

**Comment by engineers-bojan** [comment]
If i may suggest this feature in the following releases :)

But in the case i am implementing this how am i to battle socket emitting buffered events?

https://github.com/socketio/socket.io-client-java/issues/322

Consider the following situation:
I try to emit an event but the socket disconnects at that moment. The event is buffered in the socket internal variable. After a few minutes the socket reconnects and it will emit all the buffered events. There is no way to cancel buffered events or to clear those buffers.

This is a major drawback in implementing ACK timeout, since any timers/handlers i might implement that will notify me of ack timeout are potentially invalid as the socket may reconnect and emit those events and trigger the acks afterwards....the proper way would be to timeout the acks with the event buffers themselves.

-------------------------------------------------------------------------------------
Does this make sense? The only solution for now as i see it is to fork the code and make the modifications required for my project?

**Comment by AljoSt** [comment]
In order to accomplish timeout handling, one could just create a timestamp queue in the [Socket class](https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Socket.java#L19), add a timestamp [here](https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Socket.java#L203) and check the timestamp [here](https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Socket.java#L391) right?

**Comment by carlbenson** [comment]
@AljoSt did you implement this? I'm also thinking about looking into this. Wouldn't the problem with the timestamp approach be that if there is no ack ever, how could you ever check the timestamp? I think perhaps one would add some timeout [here](https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Socket.java#L334) and when the timeout occurs and the sendBuffer still contains the message, it should be removed.

**Comment by AljoSt** [comment]
@carlbenson No, unfortunately the project I used socket.io for kinda slowed down to a halt. So I didn't get to implement the workaround. As far as I remember I wanted to use two timestamp checks:
A wrapper class that that calls socket.io for emitting does it, as well as socket.io. If the time runs out, the wrapper class would call some "onTimeout" callback to let the application know about it. And socket.io would drop the message [https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Socket.java#L391](here). The timestamp is created when first emit fails [https://github.com/socketio/socket.io-client-java/blob/master/src/main/java/io/socket/client/Socket.java#L203](here). Hope that helps, but maybe I didn't get your problem since I didn't look into this for a long time :P

**Comment by darrachequesne** [comment]
Here we go:

```java
socket.emit("hello", "world", new AckWithTimeout(5000) {
    @OverRide
    public void onTimeout() {
        // ...
    }

    @OverRide
    public void onSuccess(Object... args) {
        // ...
    }
});
```

Added in version `2.1.0`.
