### ISSUE TITLE
how to solve connect error

### ISSUE THREAD

**Issue by youxikaifa** [socketio/socket.io-client-java#364]
my code :
 try {
            // http://localhost:3000/room/room_1
            mSocket = IO.socket("http://localhost:3000");
            mSocket.on(Socket.EVENT_CONNECT,onConnect);
--->            mSocket.on(Socket.EVENT_DISCONNECT,onDisconnect);
            mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
            mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
            mSocket.on("message", onNewMessage);
//            mSocket.on("join", onUserJoined);
            mSocket.connect();
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }

public Emitter.Listener onConnectError = new Emitter.Listener() {
        @Override
        public void call(Object... args) {
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(MainActivity.this, "连接错误", Toast.LENGTH_SHORT).show();
                }
            });
        }
    };

i use in my code, alway log the 连接错误？why?

**Comment by varunagarwal315** [comment]
Please convert the log to English and print the entire stack trace shows in
Android monitor so I may help you.  One very common mistake though is to
ensure the host and phone are on the same WiFi network. You can convert
from android device to the local host of a computer.  You need to connect
to the computers public ip instead.

On 1 Nov 2016 9:12 pm, "Jay" <notifications@github.com> wrote:

my code :
try {
// http://localhost:3000/room/room_1
mSocket = IO.socket("http://localhost:3000");
mSocket.on(Socket.EVENT_CONNECT,onConnect);
---> mSocket.on(Socket.EVENT_DISCONNECT,onDisconnect);
mSocket.on(Socket.EVENT_CONNECT_ERROR, onConnectError);
mSocket.on(Socket.EVENT_CONNECT_TIMEOUT, onConnectError);
mSocket.on("message", onNewMessage);
// mSocket.on("join", onUserJoined);
mSocket.connect();
} catch (URISyntaxException e) {
e.printStackTrace();
}

public Emitter.Listener onConnectError = new Emitter.Listener() {
@Override <https://github.com/Override>
public void call(Object... args) {
runOnUiThread(new Runnable() {
@Override <https://github.com/Override>
public void run() {
Toast.makeText(MainActivity.this, "连接错误", Toast.LENGTH_SHORT).show();
}
});
}
};

i use in my code, alway log the 连接错误？why?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/socketio/socket.io-client-java/issues/364>, or mute the
thread

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
