### ISSUE TITLE
socket.emit and CountDownLatch

### ISSUE THREAD

**Issue by footniko** [socketio/socket.io-client-java#617]
All I want is to wait for the result from `new Ack()` before I proceed but it looks like `socket.emit` gets never invoked if I use `CountDownLatch`. Here is my **MainActivity.java**:
```
...
     private SendTransport.Listener sendTransportListener = new SendTransport.Listener() {
        @Override
        public String onProduce(JSONObject data) {
            String result = receiveResult(data);
            return result;
        }
    };
    
    
    private String receiveResult(JSONObject data) throws InterruptedException {
        String result = "";
        final CountDownLatch latch = new CountDownLatch(1);

        socket.emit("receive-result", data, new Ack() {
            @Override
            public void call(Object... args) {
            	result = args[1];
                latch.countDown();
            }
        });

        latch.await();
        return result;
    }
...
```
Note, it works fine if I remove the `CountDownLatch` bites but I need to wait for the result somehow. How can one do this?

**Comment by ArcDexx** [comment]
It happens if you call `sendTransport.produce` in the main thread : this will call `onProduce` callback in the main thread. The `Ack` callback always happens on the main thread, so you need to be calling `sendTransport.produce` from another thread.

Right now you are blocking the main thread, meaning the callback will never be triggered.

A simple solution is 

`thread {
  sendTransport.produce(...)
}`
