### ISSUE TITLE
Unable to connect android Kotlin with python-socketio

### ISSUE THREAD

**Issue by ajju10** [socketio/socket.io-client-java#648]
I'm using the official Java socket.io client to connect to python-socketio backend with my Kotlin android app. 

I'm using the latest version of both libraries so I don't think there are any compatibility issues. 

The client never tries to connect to the server and no error messages are logged as well.

I think the server/client completely ignores each other.

Looking forward for some solution.

**Comment by MaxLuxs** [comment]
I had a problem like this.  The server has the latest version of socket.io for python.  I had a java socket.io 2.0.  The solution was to downgrade the java client version to 1.0

**Comment by ajju10** [comment]
Thanks for your support. I have found a way to make it work. 🤗

**Comment by ErsinDemirbas** [comment]
> Thanks for your support. I have found a way to make it work. 🤗

how did yu solve it

**Comment by ajju10** [comment]
You just have to find compatible versions of server and client packages as all versions are not compatible with each others.
Check compatibility table in documentation and use appropriate versions of client and server packages.

**Comment by darrachequesne** [comment]
To complete the answer above, please check the compatibility table here: https://socketio.github.io/socket.io-client-java/installation.html#Compatibility

**Comment by ErsinDemirbas** [comment]
Actually, my problem is that when I use v1 client, I can connect to old servers before v3, but the server of the company I work for uses v3, so I switch to client v2, but I can't connect to the server. I need another server url using v3 to find out if the problem is from me or from the server. Do you know a site that uses server v3 for testing? Or if your own server is using v3 and above, can you share the url as a message? I'm a newly graduated android developer, so I'm not very knowledgeable about the server side.
