### ISSUE TITLE
"transport close" fires immediately after there is no network on device

### ISSUE THREAD

**Issue by nemanjavuk** [socketio/socket.io-client-java#92]
I'm using socket.io 1.3.2 on the backend (nodejs) and the latest version (0.3.0) of this library on Nexus 5 running Android 5.0.1. Issue I'm experiencing is that when I manually cut of the Internet connection on the device (Airplane mode for example) I see in the lib that automatically closes the socket connection with "transport close" as a reason. When the connection gets back, the device sends out the disconnect event and from then on the client is disconnected. It reconnects afterwards but then I need to code a different logic on the Android client and JS client because they behave differently. You can test this by using https://github.com/nkzawa/socket.io-android-chat.

**Comment by nkzawa** [comment]
Umm, I could reproduce immediate disconnection with the reason "transport close" when no internet connection, but couldn't do that the client disconnects after the connection gets back.

What I noticed is a connection duplicates when the internet connection gets back, and old one automatically closes because of heartbeat failure. Do you mean this behavior? if not could you give me more information to reproduce the issue?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
