### ISSUE TITLE
Socket.io-client using non-daemon threads

### ISSUE THREAD

**Issue by bootups** [socketio/socket.io-client-java#93]
I am writing a Java agent, and don't have control over the source code of the actual Java application. In my Java agent code I am establishing a socket.io-client connection. When the application naturally ends I want the Shutdown listener to trigger, and I will close the socket then. However the Shutdown listener won't trigger because socket.io-client has non-daemon threads open. The application remains open indefinitely, even though all of the application threads have exited.

Would it be possible to put an option in, which when used, causes com.github.nkzawa.thread.EventThread.THREAD_FACTORY, com.github.nkzawa.socketio.client.Manager.reconnectScheduler ThreadFactory, com.github.nkzawa.socketio.client.Manager.timeoutScheduler ThreadFactory; to use daemon threads instead?

Thanks

**Comment by nkzawa** [comment]
Unfortunately, I have no thought to add such option for now. I think you should explicitly close a socket to shut down your program.
Do you have any reasons you can't do that?

**Comment by adrianb11** [comment]
My use case is different from the normal. I am writing a Java agent, and don't have control over the source code of the actual Java application. http://blog.javabenchmark.org/2013/05/java-instrumentation-tutorial.html

So my code isn't actually part of the application its an add on unit. In my add on unit, I am using socket.io-client, and the created connection is not part of the actual application. 

Normally once the application would like to complete, when all non-daemon threads are finished, I detect the shutdown process and then I close down connections etc. The problem is socket.io-client has non-daemon threads open which stops the shutdown process. And because the shutdown process never begins the application hangs.

**Comment by nkzawa** [comment]
Thank you for your explanation. I understand the library should support that. I will implement it later.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
